### ISSUE TITLE
数据库无法连接，飞书事件订阅中请求地址保存不了

### ISSUE THREAD

**Issue by lhlxx2010** [yingshang/feishu-talk#4]
大佬你好，我目前碰到2个问题，一个是运行报错如下：似乎是数据库的原因。已经安装了sqlalchemy

sqlite3.OperationalError: unable to open database file

第二个问题是飞书这边事件订阅中的请求地址，我是不是应该把ip换为我自己的ip去保存？那是不是需要先启动服务，才能有回调？
![image](https://github.com/yingshang/lanuage-talk-listen/assets/74414383/de0293ca-005b-4b5f-aa53-3e9102815908)

感谢大佬开发此项目

**Comment by lhlxx2010** [comment]
用docker跑起来了，有2个建议：
1、目前功能有点多，其实在飞书里操作不是很方便，都是命令行的形式，我觉得可以精简一些内容，我觉得重点可以放在语音对话上
2、对话的方式似乎没有框定ai的角色，所以几乎每句话ai都会说，作为一个ai模型我不能怎么怎么样，但是我可以告诉你怎么怎么样。这个就完全不是一个对话的样子。

**Comment by yingshang** [comment]
你要输入你的IP地址。你可以框定的，有个扮演角色功能

**Comment by lhlxx2010** [comment]
> 

围绕一个话题的时候，我跟他聊天。关于food，我问你喜欢吃啥，他说作为一个ai，我不吃东西，但是我推荐啥啥啥。然后关于sport，我跟他说我喜欢足球，那你呢。他又说作为一个ai我不能巴拉巴拉。

然后我原生启动，database起不来是为啥呀大佬

**Comment by yingshang** [comment]
1.我没有遇见过这种情况，你可以重开一个会话，你如果单纯练习口语，最近iPhone有个APP叫call annie，B站搜下视频。
2.你需要有台外网IP的服务器进行部署，并在飞书回调中，输入IP地址
